Simulation += sim_outletData.o \
              sim_outletInterface.o \
              sim_outletInit.o \
              sim_outletFinalize.o \
              sim_outletSetForcing.o \
              sim_outletLSDamping.o \
              sim_outletVelFrc.o \
              sim_outletVelFrcPhased.o \
              sim_outletApplyBCToRegion.o
