# This is a basic workflow that is manually triggered

name: hdf5AsyncIO

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Problem name
        description: 'Problem to setup'
        # Default value if no value is explicitly provided
        default: 'Sod'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ubuntu-latest:
    name: "ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Dependencies1
      run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git submodule update --init --recursive
          mydir="$PWD"
          sudo apt-get update
          sudo apt-get install libtool
          # zlib
          sudo apt-get install libopenmpi-dev
          sudo apt-get install zlib1g-dev 
          # python3
          sudo apt-get install python3          
          # vol async hdf5
          git clone https://github.com/hpc-io/vol-async.git
          git clone https://github.com/HDFGroup/hdf5.git
          # mpi
          export HDF5_DIR=$mydir/hdf5/install
          export ABT_DIR=$mydir/vol-async/argobots
          export VOL_DIR=$mydir/vol-async          
          mkdir $HDF5_DIR
          # Compile HDF5
          cd hdf5
          wget https://gist.githubusercontent.com/houjun/208903d8e6a64e2670754d8ca0f6b548/raw/208257da2a4cfd02e11cc45181567d48ffb47792/gistfile1.txt
          git apply gistfile1.txt
          export HDF5_LIBTOOL=/usr/bin/libtoolize
          ./autogen.sh
          ./configure --prefix=$HDF5_DIR --enable-parallel --enable-threadsafe --enable-unsupported --enable-fortran
          make && make install          
          # Compile Argobots
          cd $mydir/vol-async
          git submodule update --init --recursive
          cd $ABT_DIR
          ./autogen.sh
          ./configure --prefix=$ABT_DIR/
          make && make install          
          which mpicc
          which mpif90
          # Compile Asynchronous VOL connector
          cd $VOL_DIR/src
          tail -n 48 Makefile.summit > Makefile
          sed -i "s/CFLAGS =/CFLAGS = -DENABLE_WRITE_MEMCPY/g" ./Makefile
          make        
    - name: Flash get submodule and launch setup 
      run: |
          mydir="$PWD"
          echo $mydir
          export H5_DIR=/home/runner/work/Flash-X/Flash-X/hdf5
          export ABT_DIR=/home/runner/work/Flash-X/Flash-X/vol-async/argobots/
          export VOL_DIR=/home/runner/work/Flash-X/Flash-X/vol-async
          export LD_LIBRARY_PATH=$VOL_DIR/src:$H5_DIR/install/lib:$ABT_DIR/lib:$LD_LIBRARY_PATH
          export HDF5_PLUGIN_PATH="$VOL_DIR/src"
          export HDF5_VOL_CONNECTOR="async under_vol=0;under_info={}"             
          ./setup ${{ github.event.inputs.name }} -auto -debug -site=hello -makefile=GitHubActions +parallelIO +hdf5AsyncIO       
    - name: Flash make
      run: |
          mydir="$PWD"
          echo $mydir
          cd object
          export H5_DIR=/home/runner/work/Flash-X/Flash-X/hdf5
          export ABT_DIR=/home/runner/work/Flash-X/Flash-X/vol-async/argobots/
          export VOL_DIR=/home/runner/work/Flash-X/Flash-X/vol-async
          export LD_LIBRARY_PATH=$VOL_DIR/src:$H5_DIR/install/lib:$ABT_DIR/lib:$LD_LIBRARY_PATH
          export HDF5_PLUGIN_PATH="$VOL_DIR/src"
          export HDF5_VOL_CONNECTOR="async under_vol=0;under_info={}"   
          make -j4
    - name: Flash run
      run: |          
          mydir="$PWD"
          echo $mydir
          cd object
          export H5_DIR=/home/runner/work/Flash-X/Flash-X/hdf5
          export ABT_DIR=/home/runner/work/Flash-X/Flash-X/vol-async/argobots/
          export VOL_DIR=/home/runner/work/Flash-X/Flash-X/vol-async
          export LD_LIBRARY_PATH=$VOL_DIR/src:$H5_DIR/install/lib:$ABT_DIR/lib:$LD_LIBRARY_PATH
          export HDF5_PLUGIN_PATH="$VOL_DIR/src"
          export HDF5_VOL_CONNECTOR="async under_vol=0;under_info={}"   
          export LD_PRELOAD=$H5_DIR/install/lib/libhdf5.so:$H5_DIR/install/lib/libhdf5_fortran.so:$VOL_DIR/src/libh5async.so:$ABT_DIR/lib/libabt.so          
          mpiexec -np 2 ./flashx    
          ls -ltrh *chk*
          head -n 21 *.log
          tail -n 200 *.log          

